### ISSUE TITLE
Coversion of src/controllers/tags.js from JS to TS

### ISSUE THREAD

**Issue by ArunSaiNarla** [UCF-CEN-5016/NodeBB-UCF#103]
I woul like to convert this src/controllers/tags.js to TS

**Comment by ArunSaiNarla** [comment]
I would like to work on this file please!

**Comment by ArunSaiNarla** [comment]
I would like to work on this please!

**Comment by kpmoran** [comment]
Great! I assigned you (@ArunSaiNarla) to the issue. Have fun working on it!
