### ISSUE TITLE
Converting src/categories/watch.js from JS to TS

### ISSUE THREAD

**Issue by ArunSaiNarla** [UCF-CEN-5016/NodeBB-UCF#26]
This .js file needs to be converted into .ts

**Comment by ArunSaiNarla** [comment]
I would like to work on this please

**Comment by PappasBrent** [comment]
Hey @ArunSaiNarla, heads up that you were not automatically assigned to this issue. I think you forgot the required exclamation point at the end of your last comment.

**Comment by ArunSaiNarla** [comment]
I would like to work on this please!

**Comment by kpmoran** [comment]
Great! I assigned you (@ArunSaiNarla) to the issue. Have fun working on it!

**Comment by ArunSaiNarla** [comment]
> Hey @ArunSaiNarla, heads up that you were not automatically assigned to this issue. I think you forgot the required exclamation point at the end of your last comment.

Thanks Brent for posting this !
