### ISSUE TITLE
Converting src/social.js from JS to TS

### ISSUE THREAD

**Issue by Draxidious** [UCF-CEN-5016/NodeBB-UCF#8]
- Translating src/social.js file to typescript

**Comment by Draxidious** [comment]
I would like to work on this please!

**Comment by kpmoran** [comment]
Great! I assigned you (@Draxidious) to the issue. Have fun working on it!

**Comment by Draxidious** [comment]
I did not realize that this file was an example file that already has a typescript translation. Closing issue.
